tenant: MBDC
vrf: production
app_profile: MBDC_AppProf

bridge_domains:
- Web_BD
- App_DB
- DB_BD
- Test

epgs:
  - { bd: "Test", epg: "Epic_Lawson_245_EPG" }
  - { bd: "Test", epg: "MB_AH_Redun_699_EPG" }
  - { bd: "Test", epg: "Mail_and_Backups_151_EPG" }
  - { bd: "Test", epg: "Network_150_EPG" }
  - { bd: "Test", epg: "Servers_260_EPG" }
  - { bd: "Test", epg: "SAN_148_EPG" }
  - { bd: "Test", epg: "Servers_149_EPG" }
  - { bd: "Test", epg: "Servers_102_EPG" }
  - { bd: "Test", epg: "PXE_305_EPG" }
  - { bd: "Test", epg: "Radiology_144_EPG" }
  - { bd: "Test", epg: "Servers_216_EPG" }
  - { bd: "Test", epg: "Epic_Citrix_152_EPG" }
  - { bd: "Test", epg: "GS_MB_210_EPG" }
  - { bd: "Test", epg: "Data_Dom_246_EPG" }
  - { bd: "Test", epg: "Varian_162_EPG" }
  - { bd: "Test", epg: "QS_106_EPG" }
  - { bd: "Test", epg: "Mckesson_139_EPG" }
  - { bd: "Test", epg: "PCI_1500_EPG" }
  - { bd: "Test", epg: "Mcafee_1895_EPG" }
