tenant: BMGF
vrf: production
app_profile: IDM

bridge_domains:
- Web_BD
- App_DB
- DB_BD
- Test

epgs:
  - { bd: "Test", epg: "IDM_VL1901_DEV" }
  - { bd: "Test", epg: "IDM_VL1813_VMK_ISCSILEFT" }
  - { bd: "Test", epg: "IDM_VL1815_VMK_ISCSIRIGHT" }
  - { bd: "Test", epg: "IDM_VL1801_VMN_CORP" }
  - { bd: "Test", epg: "IDM_VL1810_VMN_CORP_DATA" }
  - { bd: "Test", epg: "IDM_VL1913_DEV_LINUX" }
  - { bd: "Test", epg: "IDM_VL1915_DEV_VM" }
  - { bd: "Test", epg: "IDM_VL1802_VMN_WORKSTATION" }
