tenant: Prod
vrf: production
app_profile: Web_App
pod: 1

bridge_domains:
- Web_BD
- App_DB
- DB_BD

epgs:
  - { bd: "Web_BD", epg: "Web" }
  - { bd: "App_BD", epg: "App" }
  - { bd: "DB_BD", epg: "DB" }

epgs_domains:
  - { domain: "phys", epg: "Web" }
  - { domain: "phys", epg: "App" }
  - { domain: "phys", epg: "DB" }


int_profile:

- { int_type: "switch_port", profile: "L101", selector: "1-10", polgro: "Auto-Access", interface: "21" }
- { int_type: "switch_port", profile: "L101", selector: "1-11", polgro: "Auto-Access", interface: "22" }
- { int_type: "switch_port", profile: "L101", selector: "1-12", polgro: "Auto-Access", interface: "23" }
- { int_type: "switch_port", profile: "L101", selector: "1-13", polgro: "Auto-Access", interface: "24" }
- { int_type: "switch_port", profile: "L101", selector: "1-14", polgro: "Auto-Access", interface: "25" }


epg_ports:
- { epg: "Web", vlan: "10", int_mode: "native", int_type: "switch_port", interface: "1/10", leaf: "101" }
- { epg: "Web", vlan: "11", int_mode: "native", int_type: "switch_port", interface: "1/11", leaf: "101" }
- { epg: "App", vlan: "12", int_mode: "native", int_type: "switch_port", interface: "1/12", leaf: "101" }
- { epg: "App", vlan: "13", int_mode: "native", int_type: "switch_port", interface: "1/13", leaf: "102" }
- { epg: "DB", vlan: "14", int_mode: "native", int_type: "switch_port", interface: "1/14", leaf: "101" }
